compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
deepspeed_config:
  zero_stage: 2
  gradient_accumulation_steps: 4
  gradient_clipping: 1.0
  offload_optimizer_device: "none"
  offload_param_device: "none"
  zero3_init_flag: false
  zero3_save_16bit_model: false
machine_rank: 0
main_training_function: main
num_machines: 1
num_processes: 4
mixed_precision: bf16
